table D_FO
	lineageTag: a15f557b-23ff-476f-a4b4-9a5577b16df7

	column lastName
		dataType: string
		lineageTag: 1b3098a7-a035-413c-a2ee-692e40d00f78
		summarizeBy: none
		sourceColumn: lastName

		annotation SummarizationSetBy = Automatic

	column birthDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: fc281e39-efa1-470f-9836-6191b48b8c0e
		summarizeBy: none
		sourceColumn: birthDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column donor_key
		dataType: string
		lineageTag: 5c9417a2-6cc8-47ca-8462-c50598001ed5
		summarizeBy: none
		sourceColumn: donor_key

		annotation SummarizationSetBy = Automatic

	column Age
		dataType: int64
		formatString: 0
		lineageTag: 689798b5-d907-40e4-a2e3-84fd963c6a76
		summarizeBy: none
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column firstName
		dataType: string
		lineageTag: a3600f8f-5a80-460c-8aa9-c71c0ca512a7
		summarizeBy: none
		sourceColumn: firstName

		annotation SummarizationSetBy = Automatic

	column Index
		dataType: int64
		formatString: 0
		lineageTag: a332c04d-f65c-40e9-b042-4d0a1be53ca7
		summarizeBy: none
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	column 'Age Band' = ```
			
			    SWITCH(TRUE(),
			        ISBLANK(D_FO[Age]),"Neuvedeno",
			        D_FO[Age] < 35, "<35",
			        D_FO[Age] < 50, "35-49",
			        D_FO[Age] < 65, "50-64",
			                       "65+"
			    )
			```
		lineageTag: 665f2a4a-d163-4119-a5c6-9fb15589e73f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition D_FO = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\jirip\Developer\python\Political_Donations\donations_fo.csv"),[Delimiter=",", Columns=12, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"year", Int64.Type}, {"ic", Int64.Type}, {"value", Int64.Type}, {"donor_type", type text}, {"description", type text}, {"firstName", type text}, {"lastName", type text}, {"titleBefore", type text}, {"titleAfter", type text}, {"birthDate", type date}, {"date", type date}, {"addrCity", type text}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each ([value] <> 0)),
				
				    #"Removed Other Columns" = Table.SelectColumns(#"Filtered Rows",{"firstName", "lastName", "birthDate"}),
				    #"Capitalized Each Word" = Table.TransformColumns(#"Removed Other Columns",{{"firstName", Text.Proper, type text}, {"lastName", Text.Proper, type text}}),
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Capitalized Each Word", "firstName", Splitter.SplitTextByDelimiter(",", QuoteStyle.Csv), {"firstName", "firstName.2"}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Split Column by Delimiter",{"firstName.2"}),
				    #"Sorted Rows" = Table.Sort(#"Removed Columns1",{{"lastName", Order.Ascending}, {"firstName", Order.Ascending}, {"birthDate", Order.Descending}}),
				    #"Removed Duplicates" = Table.Distinct(#"Sorted Rows"),
				    #"Removed Duplicates1" = Table.Distinct(#"Removed Duplicates", {"firstName", "lastName"}),
				    #"Added Custom Column" = Table.AddColumn(#"Removed Duplicates1", "Custom", each Text.Combine({[firstName], " ", [lastName], " (*", Text.Middle(Date.ToText([birthDate], "yyyy"), 2), ")"}), type text),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Custom Column",{{"Custom", "donor_key"}}),
				    #"Inserted Age" = Table.AddColumn( #"Renamed Columns", "Age", each let bd = Date.From([birthDate]), today = Date.From(DateTime.LocalNow()), years = Date.Year(today) - Date.Year(bd), hadBirthdayThisYear = if Date.Month(today) > Date.Month(bd) or (Date.Month(today) = Date.Month(bd) and Date.Day(today) >= Date.Day(bd)) then 1 else 0 in if bd = null then null else years - (if hadBirthdayThisYear = 1 then 0 else 1), Int64.Type ),
				    #"Added Index" = Table.AddIndexColumn(#"Inserted Age", "Index", 0, 1, Int64.Type)
				in
				    #"Added Index"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

